language: python
python:
  - "3.6"

sudo: required
dist: trusty

cache: pip

services:
  - docker


install:
  - pip install codecov coverage pre-commit


before_script:
  - docker run -d --name redis redis:5.0.3-alpine

script:
  - docker build . -t excars/excars-back
  - docker run --rm --link redis:redis --volume $(pwd):/excars-back excars/excars-back pytest; [ "$?" -eq 0 ] || exit $?

after_success:
  - mv .coverage .coverage.travis
  - coverage combine --append
  - codecov


before_deploy:
  wget -qO- https://toolbelt.heroku.com/install.sh | sh;
  echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin;
  echo "${HEROKU_PASSWORD}" | docker login -u "${HEROKU_USERNAME}" --password-stdin registry.heroku.com;
  docker tag excars/excars-back registry.heroku.com/${HEROKU_APP_NAME}/web

deploy:
  provider: script
  script:
    docker push excars/excars-back;
    docker push registry.heroku.com/${HEROKU_APP_NAME}/web;
    heroku container:release web --app ${HEROKU_APP_NAME}
  on:
    branch: master
