language: python
python:
  - "3.6"

sudo: required
dist: trusty

cache: pip

services:
  - docker


install:
  - pip install codecov coverage


before_script:
  - docker pull excars/excars-back
  - docker run -d --name redis redis:5.0.3-alpine

script:
  - docker build . -t excars/excars-back --cache-from excars/excars-back
  - docker run --rm --link redis:redis --volume $(pwd):/app excars/excars-back pytest; [ "$?" -eq 0 ] || exit $?

after_success:
  - mv .coverage .coverage.travis
  - coverage combine --append
  - codecov


before_deploy:
  wget -qO- https://toolbelt.heroku.com/install.sh | sh;
  echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin;
  echo "${HEROKU_PASSWORD}" | docker login -u "${HEROKU_USERNAME}" --password-stdin registry.heroku.com

deploy:
  - provider: script
    script:
      docker tag excars/excars-back registry.heroku.com/${HEROKU_APP_STAGE_NAME}/web;
      docker push registry.heroku.com/${HEROKU_APP_STAGE_NAME}/web;
      heroku container:release web --app ${HEROKU_APP_STAGE_NAME}
    on:
      branch: master
  - provider: script
    script:
      docker tag excars/excars-back registry.heroku.com/${HEROKU_APP_PROD_NAME}/web;
      docker push excars/excars-back;
      docker push registry.heroku.com/${HEROKU_APP_PROD_NAME}/web;
      heroku container:release web --app ${HEROKU_APP_PROD_NAME}
    on:
      branch: tags
