language: python
python:
  - "3.6"

sudo: required
dist: trusty

services:
  - docker

before_install:
  - touch secrets.env
  - docker-compose build

install:
  - pip install codecov
  - pip install coverage==5.0a3

script:
  - docker-compose run app make ci

after_script:
  - docker-compose down


after_success:
  - mv .coverage .coverage.travis
  - coverage combine --append
  - codecov
