version: '3'


services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${EXTERNAL_PORT}:80
    volumes:
      - .:/app
    environment:
      MODULE_NAME: excars.main
    env_file:
    - ./secrets.env
    depends_on:
      - db
      - redis
    command: /start-reload.sh

  db:
    restart: always
    image: postgres:alpine
    environment:
      POSTGRES_DB: excars
      POSTGRES_USER: excars
      POSTGRES_PASSWORD: excars
    expose:
      - "5432"

  redis:
    restart: always
    image: redis:5-alpine
