version: '3'


services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${EXTERNAL_PORT}:80
    volumes:
      - .:/app
    environment:
      MODULE_NAME: excars.main
    env_file:
    - ./secrets.env
    depends_on:
      - redis
    command: /start-reload.sh

  redis:
    restart: always
    image: redis:5-alpine
